"""Export engine: JSON / CSV / Markdown / PDF — all from the same AnalysisResult."""
import csv
import io
import json

from app import schemas

BLOOM_ORDER = ["remember", "understand", "apply", "analyze", "evaluate", "create"]


def to_json(result: schemas.AnalysisResult) -> tuple[bytes, str]:
    payload = result.model_dump(mode="json")
    return json.dumps(payload, indent=2).encode("utf-8"), "application/json"


def to_csv(result: schemas.AnalysisResult) -> tuple[bytes, str]:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["# Concepto export", result.title])
    w.writerow(["# Content Type", result.content_type, "Coverage Score", f"{result.coverage_score:.1f}%", "Avg Confidence", f"{result.avg_confidence:.1%}"])
    w.writerow([])
    w.writerow(["OBJECTIVES"])
    w.writerow(["id", "objective", "bloom_level", "confidence", "kind", "skills", "concepts"])
    for o in result.objectives:
        w.writerow([o.id, o.text, o.bloom_level, o.confidence, o.kind,
                    "; ".join(o.skills), "; ".join(o.concepts)])
    w.writerow([])
    w.writerow(["SKILLS"])
    w.writerow(["skill", "frequency", "confidence", "bloom_levels"])
    for s in result.skills:
        w.writerow([s.name, s.frequency, s.confidence, "; ".join(s.bloom_levels)])
    w.writerow([])
    w.writerow(["CONCEPTS"])
    w.writerow(["concept", "definition", "importance"])
    for c in result.concepts:
        w.writerow([c.name, c.definition, c.importance])
    w.writerow([])
    w.writerow(["ASSESSMENTS - MULTIPLE CHOICE QUESTIONS"])
    w.writerow(["question_number", "bloom_level", "question", "options", "correct_answer", "explanation"])
    for i, m in enumerate(result.assessments.mcqs, 1):
        correct_text = m.options[m.answer_index] if 0 <= m.answer_index < len(m.options) else ""
        w.writerow([i, m.bloom_level, m.question, " | ".join(m.options), correct_text, m.explanation or ""])
    w.writerow([])
    w.writerow(["ASSESSMENTS - SHORT ANSWERS & TASKS"])
    w.writerow(["type", "bloom_level", "title_or_question", "details_or_answer"])
    for s in result.assessments.short_answers:
        w.writerow(["Short Answer", s.bloom_level, s.question, s.sample_answer or ""])
    for t in result.assessments.practical_tasks:
        w.writerow(["Practical Task", t.bloom_level, t.title, t.description])
    for p in result.assessments.projects:
        w.writerow(["Project", "create", p.title, p.description])
    w.writerow([])
    w.writerow(["GAPS"])
    w.writerow(["category", "severity", "title", "recommendation"])
    for g in result.gaps:
        w.writerow([g.category, g.severity, g.title, g.recommendation])
    return buf.getvalue().encode("utf-8"), "text/csv"


def to_markdown(result: schemas.AnalysisResult) -> tuple[bytes, str]:
    L = [f"# {result.title}", "",
         f"> {result.summary}" if result.summary else "", "",
         f"- **Content type:** {result.content_type}",
         f"- **Objectives:** {len(result.objectives)}  |  **Skills:** {len(result.skills)}  |  "
         f"**Avg confidence:** {result.avg_confidence:.0%}  |  **Coverage:** {result.coverage_score:.0f}/100",
         "", "## Learning Objectives", ""]
    for lvl in BLOOM_ORDER:
        objs = [o for o in result.objectives if o.bloom_level == lvl]
        if not objs:
            continue
        L.append(f"### {lvl.capitalize()} ({len(objs)})")
        for o in objs:
            L.append(f"- {o.text} `{(o.confidence):.0%}` `{o.kind}`")
        L.append("")
    L += ["## Key Concepts", ""]
    for c in result.concepts:
        L.append(f"- **{c.name}** — {c.definition}")
    L += ["", "## Skills", ""]
    for s in result.skills:
        L.append(f"- **{s.name}** (x{s.frequency}, {(s.confidence):.0%})")
    L += ["", "## Assessments", ""]
    for i, m in enumerate(result.assessments.mcqs, 1):
        L.append(f"**Q{i}.** {m.question}")
        for j, opt in enumerate(m.options):
            mark = "✅" if j == m.answer_index else "▫️"
            L.append(f"  {mark} {opt}")
        if m.explanation:
            L.append(f"  *Explanation:* {m.explanation}")
        L.append("")
    for q in result.assessments.short_answers:
        L.append(f"- *Short answer:* {q.question}")
        if q.sample_answer:
            L.append(f"  *Sample:* {q.sample_answer}")
    for t in result.assessments.practical_tasks:
        L.append(f"- *Task:* **{t.title}** — {t.description}")
    for p in result.assessments.projects:
        L.append(f"- *Project:* **{p.title}** — {p.description}")
    L += ["", "## Gap Analysis", ""]
    for g in result.gaps:
        L.append(f"- **[{g.severity.upper()}] {g.title}** — {g.description} → *{g.recommendation}*")
    L += ["", f"*Generated by Concepto (engine: {result.engine})*"]
    return "\n".join(L).encode("utf-8"), "text/markdown"


def to_pdf(result: schemas.AnalysisResult) -> tuple[bytes, str]:
    from fpdf import FPDF

    def clean(s: str) -> str:
        return (s or "").encode("latin-1", "replace").decode("latin-1")

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 18)
    pdf.multi_cell(0, 10, clean(result.title), new_x="LMARGIN", new_y="NEXT")
    if result.summary:
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(100, 116, 139)
        pdf.multi_cell(0, 6, clean(result.summary), new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, clean(f"Objectives: {len(result.objectives)}   |   Skills: {len(result.skills)}   |   "
                         f"Avg confidence: {result.avg_confidence:.0%}   |   Coverage: {result.coverage_score:.0f}/100"),
             new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # Objectives grouped by Bloom level
    for lvl in BLOOM_ORDER:
        objs = [o for o in result.objectives if o.bloom_level == lvl]
        if not objs:
            continue
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_fill_color(37, 99, 235)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(0, 7, clean(f"  {lvl.capitalize()} ({len(objs)})"), new_x="LMARGIN", new_y="NEXT", fill=True)
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Helvetica", "", 9.5)
        for o in objs:
            pdf.multi_cell(0, 5.5, clean(f"- {o.text}  [{o.confidence:.0%}, {o.kind}]"), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)

    # Key Concepts
    if result.concepts:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 7, "Key Concepts", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9.5)
        for c in result.concepts[:15]:
            pdf.multi_cell(0, 5.5, clean(f"- {c.name}: {c.definition}"), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)

    # Assessments (MCQs & Short Answers)
    if result.assessments.mcqs or result.assessments.short_answers:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 7, "Assessments", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9.5)
        for i, m in enumerate(result.assessments.mcqs[:10], 1):
            pdf.set_font("Helvetica", "B", 9.5)
            pdf.multi_cell(0, 5, clean(f"Q{i}. {m.question}"), new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 9)
            for j, opt in enumerate(m.options):
                mark = "[*]" if j == m.answer_index else "[ ]"
                pdf.multi_cell(0, 4.5, clean(f"   {mark} {opt}"), new_x="LMARGIN", new_y="NEXT")
            pdf.ln(1)
        for s in result.assessments.short_answers[:5]:
            pdf.set_font("Helvetica", "I", 9.5)
            pdf.multi_cell(0, 5, clean(f"- Short Answer: {s.question}"), new_x="LMARGIN", new_y="NEXT")
            if s.sample_answer:
                pdf.set_font("Helvetica", "", 8.5)
                pdf.multi_cell(0, 4.5, clean(f"  Sample: {s.sample_answer}"), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)

    # Gap Analysis
    if result.gaps:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 7, "Gap Analysis", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9.5)
        for g in result.gaps:
            pdf.multi_cell(0, 5.5, clean(f"- [{g.severity.upper()}] {g.title}: {g.recommendation}"), new_x="LMARGIN", new_y="NEXT")

    pdf.ln(3)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(148, 163, 184)
    pdf.cell(0, 5, clean(f"Generated by Concepto (engine: {result.engine})"), new_x="LMARGIN", new_y="NEXT")
    out = bytes(pdf.output())
    return out, "application/pdf"


EXPORTERS = {"json": to_json, "csv": to_csv, "md": to_markdown, "markdown": to_markdown, "pdf": to_pdf}
EXTENSIONS = {"json": "json", "csv": "csv", "md": "md", "markdown": "md", "pdf": "pdf"}
