[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "concepto-ai"
version = "1.0.0"
description = "Concepto AI: Bloom's Taxonomy Extraction and Gemini Pipeline"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-generativeai>=0.8.4"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["ai*"]
